# Generated by Django 6.0 on 2026-01-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='questioncollection',
            name='questions',
        ),
        migrations.CreateModel(
            name='EntryV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('nicknames', models.CharField(max_length=500)),
                ('birthday', models.DateField()),
                ('size', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('likes', models.CharField(max_length=500)),
                ('dislikes', models.CharField(max_length=500)),
                ('best_experience', models.TextField()),
                ('favorite_food', models.CharField(max_length=500)),
                ('favorite_animal', models.CharField(max_length=500)),
                ('favorite_book', models.CharField(max_length=500)),
                ('favorite_movie', models.CharField(max_length=500)),
                ('favorite_music', models.CharField(max_length=500)),
                ('favorite_activity', models.CharField(max_length=500)),
                ('dream', models.TextField()),
                ('want_to_become', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blume.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCollection',
        ),
    ]
