# Generated by Django 6.0 on 2026-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blume', '0003_alter_entryv1_owner_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryv1',
            name='best_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='dislikes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='dream',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_activity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_animal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_music',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='likes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='nicknames',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='want_to_become',
            field=models.TextField(blank=True, null=True),
        ),
    ]
