# Generated by Django 6.0 on 2026-01-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('nicknames', models.CharField(blank=True, max_length=500, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=500, null=True)),
                ('dislikes', models.CharField(blank=True, max_length=500, null=True)),
                ('best_experience', models.TextField(blank=True, null=True)),
                ('favorite_food', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_animal', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_book', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_movie', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_music', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_activity', models.CharField(blank=True, max_length=500, null=True)),
                ('dream', models.TextField(blank=True, null=True)),
                ('want_to_become', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
